### PR TITLE
MSVC's strdup() in _DEBUG mode

### PR DESCRIPTION
**Pull request by gvanem**
In MSVC debug-mode (`-MDd` or `-MTd`), there is an important warning on
the redefinition of `strdup`:
```
  portability.h(104): warning C4005: 'strdup': macro redefinition
  f:\ProgramFiler-x86\WindowsKits\Include\10.0.10586.0\ucrt\crtdbg.h(319):
    note: see previous definition of 'strdup'
```
It's definition is:
```
  #define strdup(s)  _strdup_dbg(s, _NORMAL_BLOCK, __FILE__, __LINE__)
```
Undoing that in `"portability.h"` would defeat the purpose of `_DEBUG` mode.

### CODE REVIEW

**Comment by infrastation** [comment]
This is how GitHub works: 1 pull request = 1 branch, even if you add more commits to the branch later. As a side note, instead of the merge commit you could have rebased on the master branch to make the history look a little bit simpler (not critical).

**Comment by gvanem** [comment]
@infrastation rebased on the master branch ..

You mean, I should run `git rebase` locally here? Not sure what that does.

I'm really tempted to just delete my `gvanem/libpcap` repo after every PR I get merged into `the-tcpdump-group/libpcap`. Thus making git loose any *hidden* state it's keeping.

**Comment by infrastation** [comment]
`git rebase master` will put your local changes in the current branch on top of your local master branch. The other thing is, the local master branch will need to have the changes that the-tcpdump-group has, please see the example commands in tcpdump's `CONTRIBUTING` file if you want to try it.

Alternatively, deleting the local repository and starting from scratch will achieve the same effect, I did this for quite a long time until I found the right documentation and learned how it works. It does not really matter which commands you use, it matters what gets recorded in the commit history.

Ah, and since recently there's a "rebase" pull request merge option on GitHub, so we can probably just try it and see if it does the job right.

**Comment by guyharris** [comment]
> It's definition is

By "its definition" do you mean "*Microsoft's* definition"?

If any version of MSVC is defining `strdup`, and it's a definition that makes it work like UN\*X's `strdup()`, e.g.

    #define strdup _strdup

then, if we're compiling with that version of MSVC, we shouldn't be defining `strdup` *at all*, debug mode or no.

Microsoft's *documentation* of `strdup()`, for [VS 2005](https://msdn.microsoft.com/en-us/library/ms235454(v=vs.80).aspx) through [VS 2015](https://msdn.microsoft.com/en-us/library/ms235454(v=vs.140).aspx), says those functions are deprecated and that " the ISO C++ conformant _strdup ..." should be used instead.

Presumably they're deprecated to avoid namespace pollution, i.e. somebody might have written a program for C on Windows and had their own `strdup()` function, which might not have the same signature, and that should be allowed.  It's probably allowed on UN\*X if you set the right flags to keep non-ISO C functions out of the namespace.

But the question here is whether there are any versions of Visual Studio where `strdup()` is deprecated but is present in the namespace by default; if so, we should avoid defining `strdup` on those versions of VS.

**Comment by gvanem** [comment]
> But the question here is whether there are any versions of Visual Studio where strdup() is 
> deprecated but is present in the namespace by default; if so, we should avoid defining strdup 
> on those versions of VS.

That would only add to the `ifdef`-mess. But it's not really important for me to enable debug-mode in Wpcap. My intention with it was to find memory leaks. But I failed to find any! 

And `strdup` etc. exists in *all* versions of MSVC (in `oldnames.lib`). The annoying POSIX warning (since MSVC 2012?), can be disabled using `-D _CRT_NONSTDC_NO_WARNINGS --D_CRT_OBSOLETE_NO_WARNINGS`. No big deal.

So that leaves the patch for `PacketSetDumpLimits()` as more important IMHO... before I update the `msdos/*` stuff.

**Pull request merged**
