### PR TITLE
Remove code related to obsolete HW TurboCap

### PR DESCRIPTION
**Pull request by AndersBroman**
Riverbed TurboCap hardware has reached EOA has of Jun 30, 2014. There is no further support available.
Latest Drivers from Jan 18, 2010

### CODE REVIEW

**Comment by AndersBroman** [comment]
Any way to rerun the failing test? I don't se anything wrong.

**Comment by guyharris** [comment]
> Any way to rerun the failing test?

If you have a GitHub account, you might be able to restart it by going to the page for that build (the "Details" link) and clicking the appropriate link - there's a link to restart the build, if none of the individual builds have succeeded, and another to rebuild the incomplete builds, if some have succeeded.

I've restarted the build to rebuild the incomplete builds.

> I don't se anything wrong.

What's wrong is that Appveyor's networking isn't the most reliable.

**Comment by infrastation** [comment]
Rebased on the current master branch and fixed typos in the change log.

**Comment by infrastation** [comment]
Thank you.

**Pull request merged**
