### PR TITLE
Numeric truncation at `pcap-usb-linux-common.c:95`

### PR DESCRIPTION
**Pull request by headshog**
Hi! We've been fuzzing `libpcap` with [sydr-fuzz](https://github.com/ispras/oss-sydr-fuzz) security predicates and we found numeric truncation error in `pcap-usb-linux-common.c:95`.

In function `fix_linux_usb_mmapped_length` on line 95 variable `pre_truncation_len` has type `u_int` (aka unsigned int), on the right side of operator= `sizeof` promotes type to `unsigned long`, so the numeric truncation may occur. Then `pre_truncation_len` is used in if operator on line 103, so the truncation may cause wrong behavior. We suggest to change the type `u_int` of the variable `pre_truncation_len` to type `unsigned long`. 

Or if this truncation was made by design, please inform about this. 

### Environment

- OS: ubuntu 20.04
- commit: cff41e58f2fcd2c2ee77e9e25c63813e879657e1

### How to reproduce this error

1. Build [docker container](https://github.com/ispras/oss-sydr-fuzz/tree/master/projects/libpcap):

    ```
    sudo docker build -t oss-sydr-fuzz-libpcap .

    ```

2. Run docker container:

    ```
    sudo docker run --privileged --network host -v /etc/localtime:/etc/localtime:ro --rm -it -v $PWD:/fuzz oss-sydr-fuzz-libpcap /bin/bash

    ```

3. Run on the following [input](https://github.com/the-tcpdump-group/libpcap/files/12071318/sydr_f722d3ad2bfa6692ec8d54402099e2afc5d99826_num_trunc_0_unsigned.txt):

    ```
     /libpcap/libfuzzer/fuzz_pcap sydr_f722d3ad2bfa6692ec8d54402099e2afc5d99826_num_trunc_0_unsigned.txt

    ```
4. Output:

    ```
    ../pcap-usb-linux-common.c:95:24: runtime error: implicit conversion from type 'unsigned long' of value 8589934574 (64-bit, unsigned) to type 'u_int' (aka 'unsigned int') changed the value to 4294967278 (32-bit, unsigned)
    SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior ../pcap-usb-linux-common.c:95:24
    ```

### CODE REVIEW

**Comment by guyharris** [comment]
> sizeof promotes type to unsigned long

By which you presumably mean "promotes type to `size_t`".  that code is run on all platforms ("linux" in the file name refers to the operating system that defines the header format, not the only OS on which the code runs), and at least one platform that libpcap supports is an LLP64 platform, in which `{unsigned} int` is 32 bits, `{unsigned} long` is 32 bits, `{unsigned} long long` is 64 bits, `{anything} *` is 64 bits, and `size_t` is 64 bits.  (Hint: that platform comes from a company headquartered in Redmond, WA, USA.)

So `size_t`, not `unsigned long`, should be used.

However, that code needs some more work, because if `pre_truncation_len` doesn't fit in 32 bits, We Have A Problem; pcap and pcapng files have 32-bit fields for packet captured length and unsliced length, and the libpcap API uses 32-bit fields for that purpose.

For now, just use `size_t`, and I'll look at what more needs to be done.

**Comment by headshog** [comment]
> > sizeof promotes type to unsigned long
> 
> By which you presumably mean "promotes type to `size_t`". that code is run on all platforms ("linux" in the file name refers to the operating system that defines the header format, not the only OS on which the code runs), and at least one platform that libpcap supports is an LLP64 platform, in which `{unsigned} int` is 32 bits, `{unsigned} long` is 32 bits, `{unsigned} long long` is 64 bits, `{anything} *` is 64 bits, and `size_t` is 64 bits. (Hint: that platform comes from a company headquartered in Redmond, WA, USA.)
> 
> So `size_t`, not `unsigned long`, should be used.
> 
> However, that code needs some more work, because if `pre_truncation_len` doesn't fit in 32 bits, We Have A Problem; pcap and pcapng files have 32-bit fields for packet captured length and unsliced length, and the libpcap API uses 32-bit fields for that purpose.
> 
> For now, just use `size_t`, and I'll look at what more needs to be done.

@guyharris. I have changed type `unsigned long` to `size_t` as you suggested.

**Comment by fxlb** [comment]
@headshog Could you check your "How to reproduce this error"?
The step 1 is blocked at:
```
Step 9/10 : RUN ./build.sh
[...]
checking lex library...
```

**Comment by kobrineli** [comment]
@fxlb 
Checked docker building, reproduced the block.
But it is actually is not blocked, for some reason it is checking `lex` for a very long time.
I've waited for 5 minutes and then it continued.

**Comment by guyharris** [comment]
df1d38ef680ef4ddcb390d633ddcc7a770ffdb05 should address this.

**Comment by infrastation** [comment]
Looks like the container either uses something on a very slow network to bootstrap, or performs some other activities while doing it.

**Comment by guyharris** [comment]
> How to reproduce this error

Is there a set of instructions for reproducing this error that doesn't include the phrase "docker container"?  That seems like overkill for something that should be reproducible more simply.

**Comment by fxlb** [comment]
> For example, on my computer this container was built in 30 minutes.
> `[+] Building 1751.7s (14/14) FINISHED`

It is not the same container. The one documented in this PR has 10 steps.

**Comment by headshog** [comment]
> > For example, on my computer this container was built in 30 minutes.
> > `[+] Building 1751.7s (14/14) FINISHED`
> 
> It is not the same container. The one documented in this PR has 10 steps.

I have copied the first line of docker build info it usually includes some internal steps . This is the whole info:

[+] Building 1751.7s (14/14) FINISHED                                                                                                                                                                                                                                               
   => [internal] load build definition from Dockerfile                                                                                                                                                                                                                           0.0s
   => => transferring dockerfile: 1.20kB                                                                                                                                                                                                                                         0.0s
   => [internal] load .dockerignore                                                                                                                                                                                                                                              0.0s
   => => transferring context: 2B                                                                                                                                                                                                                                                0.0s
   => [internal] load metadata for docker.io/sydr/ubuntu20.04-sydr-fuzz:latest                                                                                                                                                                                                   1.4s
   => [internal] load build context                                                                                                                                                                                                                                              0.0s
   => => transferring context: 3.91kB                                                                                                                                                                                                                                            0.0s
   => [ 1/10] FROM docker.io/sydr/ubuntu20.04-sydr-fuzz [...]
   => [ 2/10] RUN apt-get update && apt-get install -y make cmake flex bison                                                                                                                                                                                                     8.2s
   => [ 3/10] RUN git clone https://github.com/the-tcpdump-group/libpcap.git libpcap                                                                                                                                                                                             3.4s 
   => [ 4/10] RUN git clone --depth=1 https://github.com/the-tcpdump-group/tcpdump.git tcpdump                                                                                                                                                                                   1.7s 
   => [ 5/10] RUN mkdir corpus && mv tcpdump/tests/*.pcap corpus/                                                                                                                                                                                                                3.1s 
   => [ 6/10] WORKDIR libpcap                                                                                                                                                                                                                                                    0.1s 
   => [ 7/10] RUN git checkout cff41e58f2fcd2c2ee77e9e25c63813e879657e1                                                                                                                                                                                                          0.5s 
   => [ 8/10] COPY build.sh load_sydr_filter.c load_sydr_pcap.c ./                                                                                                                                                                                                               0.1s 
   => [ 9/10] RUN ./build.sh                                                                                                                                                                                                                                                  1668.0s
   => exporting to image                                                                                                                                                                                                                                                         0.3s 
   => => exporting layers                                                                                                                                                                                                                                                        0.3s 
   => => writing image sha256:03980f3d23df4a69876ed510dff74c57e44ab19f9e10c37acf3d52dac60059b6                                                                                                                                                                                   0.0s 
   => => naming to docker.io/library/oss-sydr-fuzz-libpcap`

**Pull request closed without merging**
