### PR TITLE
socketcan: make CAN CC/FD/XL frame handling less invasive

### PR DESCRIPTION
**Pull request by hartkopp**
The different CAN frame types are defined by Linux SLL_P types in the sll_protocol field and the length of the frame.

LINUX_SLL_P_CANXL:
The frame length for CAN XL can be 12 + 1 to 12 + 2048 (13 .. 2060) byte. Additionally the CANXL_XLF flag has to be set.

LINUX_SLL_P_CAN and LINUX_SLL_P_CANFD:
The frame length for CAN CC is 16 byte and for CAN FD it is 72 byte. Additionally the CANXL_XLF flag is cleared in CAN CC/FD frames.

Reduce the modification and 'sanitizing' efforts only to the above requirements to be robust against incompliant content which might be provided via PACKET sockets but do not manipulate further content.

This helps to identify uninitialized data and to support new features in formerly reserved structure elements without changing the libpcap.

### CODE REVIEW

**Comment by guyharris** [comment]
So which mechanisms can, in all versions of the Linux kernel starting with 2.6.27, reliably be counted on to provide a classic/FD/XL indication?  Is it sufficient just to check the protocol field - and then ensure that whatever flag bits are necessary to be set or clean to conform to [the LINKTYPE_CAN_SOCKETCAN specification](https://www.tcpdump.org/linktypes/LINKTYPE_CAN_SOCKETCAN.html) are set or cleared?

**Comment by hartkopp** [comment]
**Inside** the kernel the different CAN frames are transported in skbuff structures with their own ETH_P type.

See in include/uapi/linux/if_ether.h
```
#define ETH_P_CAN       0x000C          /* CAN: Controller Area Network */
#define ETH_P_CANFD     0x000D          /* CANFD: CAN flexible data rate*/
#define ETH_P_CANXL     0x000E          /* CANXL: eXtended frame Length */
```


See in af_can.c (the forced setting of CANFD_FDF was added recently)
```
int can_send(struct sk_buff *skb, int loop)
{
        struct sk_buff *newskb = NULL;
        struct can_pkg_stats *pkg_stats = dev_net(skb->dev)->can.pkg_stats;
        int err = -EINVAL;

        if (can_is_canxl_skb(skb)) {
                skb->protocol = htons(ETH_P_CANXL);
        } else if (can_is_can_skb(skb)) {
                skb->protocol = htons(ETH_P_CAN);
        } else if (can_is_canfd_skb(skb)) {
                struct canfd_frame *cfd = (struct canfd_frame *)skb->data;

                skb->protocol = htons(ETH_P_CANFD);

                /* set CAN FD flag for CAN FD frames by default */
                cfd->flags |= CANFD_FDF;
        } else {
                goto inval_skb;
        }
```

These ETH_P types are also set correctly by the CAN hardware drivers - and they are visible via the PF_PACKET socket.

When it comes to the reading from a CAN_RAW socket, the user can enable the reception of CAN FD and CAN XL traffic via setsockopt() syscalls. When both are **enabled** a read() syscall can either deliver a CAN CC/FD/XL frame.

And then the check sequence in user space  is done like in this example:
https://github.com/linux-can/can-utils/blob/master/canlogserver.c#L404

1. Check for the minimum CAN XL size and the CANXL_XLF bit set -> CAN XL
2. Check for the CAN_MTU (== 16) -> CAN CC
3. Check for the CANFD_MTU (== 72) -> CAN FD
4. No match in the above checks -> failure

This sequence is stable and works on all Linux kernels since 2.6.25 (when SocketCAN became mainline).

And I thought this simple sequence could also be a candidate for libpcap.

**Comment by hartkopp** [comment]
Additional comment:

The reason why CANXL_XLF is set resp. cleared in this libpcap patch is because of a bad player might create ETH_P_CANXL frames via PF_PACKET socket that has not set the CANXL_XLF bit.

But with the LINKTYPE_CAN_SOCKETCAN you face the same situation as when reading from a CAN_RAW socket (one buffer of some length you need to evaluate). And therefore the CANXL_XLF bit and the tvb_reported_length() are vital for a proper distinction of the CAN CC/FD/XL frame.

**Comment by guyharris** [comment]
So I see several ways of determining the flavor of CAN:

1. Look at the protocol field - that works when capturing, but the `LINKTYPE_CAN_SOCKETCAN` header doesn't include the protocol, so it won't work when reading the capture.  (At one point we used a full `LINKTYPE_LINUX_SLL` header, but, in issue #1052, somebody complained, because it doubled the size of capture files, so we went back to `LINKTYPE_CAN_SOCKETCAN`.)
2. Look at the flag bits - as long as all versions of the kernel that support CAN FD set the FD flag for FD frames and all versions of the kernel that support CAN XL set the XL flag for XL frames, that should be sufficient, unless older versions of the kernel can't be relied on to make sure the FD and XL flags are *clear* for classic CAN frames and the XL flag is clear for CAN FD frames.
3. Look at the frame lengths - I infer from "Check for the minimum CAN XL size and the CANXL_XLF bit set -> CAN XL" that this doesn't suffice for CAN XL, but it can be used by itself to distinguish between classic and FD.

**Comment by hartkopp** [comment]
> So I see several ways of determining the flavor of CAN:
> 
>     1. Look at the protocol field - that works when capturing, but the `LINKTYPE_CAN_SOCKETCAN` header doesn't include the protocol, so it won't work when reading the capture.  (At one point we used a full `LINKTYPE_LINUX_SLL` header, but, in issue [Dont add DLT_LINUX_SLL headers for CAN dumps. #1052](https://github.com/the-tcpdump-group/libpcap/issues/1052), somebody complained, because it doubled the size of capture files, so we went back to `LINKTYPE_CAN_SOCKETCAN`.)

Unfortunately I was not involved in this discussion. And today I'm not sure how not make a better "backwards compatible" improvement, than probably this patch here ...

>     2. Look at the flag bits - as long as all versions of the kernel that support CAN FD set the FD flag for FD frames and all versions of the kernel that support CAN XL set the XL flag for XL frames, that should be sufficient, unless older versions of the kernel can't be relied on to make sure the FD and XL flags are _clear_ for classic CAN frames and the XL flag is clear for CAN FD frames.

The CANXL_XLF bit is safe but the CANFD_FDF bit has been introduced in 2022 (10 years after CAN FD support). And we can not be sure about out-of-tree CAN hardware drivers:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/net/can/af_can.c?id=061834624c87282c6d9d8c5395aaff4380e5e1fc 

>     3. Look at the frame lengths - I infer from "Check for the minimum CAN XL size and the CANXL_XLF bit set -> CAN XL" that this doesn't suffice for CAN XL, but it can be used by itself to distinguish between classic and FD.

Yes. When we have the minimum CAN XL frame size, we are also safe to access the canxl_frame.flags element when checking for the CANXL_XLF flag.
This is really a different approach from the CAN CC/FD length-only check as the CAN XL frames are only of the size that the data content fits into the frame. Otherwise we always would need to copy 2060 bytes - even if we only had one byte data size.

**Comment by hartkopp** [comment]
Summarizing the situation after getting some sleep:

When going back from DLT_LINUX_SLL to DLT_CAN_SOCKETCAN we went back from a three lane highway to a single lane road. Therefore the CAN frames going through this single lane road have to be self-contained in a way that we can evaluate the buffer and get the information about the CAN CC/FD/XL status.

Before CAN XL this was easy for Wireshark: 
```
            if (tvb_reported_length(tvb) == 72)
                can_packet_type = PACKET_TYPE_CAN_FD;
            else if  (tvb_reported_length(tvb) == 16)
                can_packet_type = PACKET_TYPE_CAN;
```
As the tvb_reported_length() is the right marker for CC/FD detection I wondered why there was a discussion about CANFD_FDF and all the sanitizing efforts?!? Libpcap and Wireshark should just display the content and not modifying it.

With CAN XL we now need to check for the CANXL_XLF bit first and then check for CAN FD/CC in Wireshark:

```
        canxl_flags = tvb_get_guint8(tvb, CANXL_FLAGS_OFFSET);
        if ((tvb_reported_length(tvb) > 12) && (canxl_flags & CANXL_XLF)) {
            can_packet_type = PACKET_TYPE_CAN_XL;
        } else {
            if (tvb_reported_length(tvb) == 72)
                can_packet_type = PACKET_TYPE_CAN_FD;
            else if  (tvb_reported_length(tvb) == 16)
                can_packet_type = PACKET_TYPE_CAN;
        }
```
When all these conditions are not met, the can_packet_type remains PACKET_TYPE_UNKNOWN.
And for Wireshark this is addressed with this patch:
https://gitlab.com/wireshark/wireshark/-/merge_requests/14886/diffs?commit_id=942125a423dbe05313518e0c745cd7cb986491c5

These two patches just implement the rules how to encode and decode the self-contained CAN frames on the single lane road analog to the reading of CAN CC/FD/XL frames from a CAN_RAW socket.

**Comment by hartkopp** [comment]
Hello @guyharris ,

to answer your question above about the `CANFD_FDF` flag I updated the LINKTYPE_CAN_SOCKETCAN documentation and sent a pull request for the HTML code: https://github.com/the-tcpdump-group/tcpdump-htdocs/pull/36

The PR for Wireshark has already been merged: https://gitlab.com/wireshark/wireshark/-/merge_requests/14886

Do you still have concerns about merging this patch? It also enables the display of the Len 8 DLC value for CAN CC frames.
https://gitlab.com/wireshark/wireshark/-/merge_requests/14886/diffs?commit_id=a98b35d98884344400b20aad815473e39f28b20d

**Comment by hartkopp** [comment]
Ping?

**Pull request closed without merging**
