### PR TITLE
CI: add an ARM64 build for AppVeyor.

### PR DESCRIPTION
**Pull request by guyharris**
(Test only on AppVeyor, so:)

[skip ci]

### CODE REVIEW

**Comment by guyharris** [comment]
> Why an update to gencode.c for an ARM64 build?

As per the updated commit message.  The volatiles are only there due to the setjmp/longjmp, and aren't being accessed from multiple threads, so the [memory model](https://en.wikipedia.org/wiki/Memory_model_(programming)) shouldn't matter here.

**Comment by guyharris** [comment]
Most if not all of this is unintentional infinite recursion, fixed in 9f368821e10e32de9fbd7aaea3e01c25c0086d48.

Next step - have the libpcap buildbot builds compile the test programs and run tests, starting with the simple test `testprogs/filtertest EN10MB`, which would have caught this *before* it was committed and used in tcpdump tests.

**Comment by guyharris** [comment]
> Next step - have the libpcap buildbot builds compile the test programs and run tests, starting with the simple test `testprogs/filtertest EN10MB`, which would have caught this _before_ it was committed and used in tcpdump tests.

That's pull request #1394.

**Comment by infrastation** [comment]
I thought the tcpdump segfault on freebsd-aarch64 was a botched FreeBSD upgrade, and was going to reinstall it from scratch.

**Comment by guyharris** [comment]
> I thought the tcpdump segfault on freebsd-aarch64 was a botched FreeBSD upgrade, and was going to reinstall it from scratch.

Sorry about that. That was my first guess when I saw the issue, but when I saw that it'd hit every buildbot, I ruled a system problem out.

**Pull request merged**
