### PR TITLE
tests: provide our own version of the timeout command.

### PR DESCRIPTION
**Pull request by guyharris**
That way, we don't have to worry about whether a platform has that command (which is not in the latest POSIX) or, if it does, whether it behaves in a particular fashion.

### CODE REVIEW

**Comment by infrastation** [comment]
These changes do not undo the installation and use (`TIMEOUT_BIN`) of coreutils on macOS. Also the commit message has three typos.

**Comment by guyharris** [comment]
> These changes do not undo the installation and use (TIMEOUT_BIN) of coreutils on macOS.

That installation didn't appear to prevent a tcpdump build from failing on macOS:

https://github.com/the-tcpdump-group/tcpdump/pull/1256/checks?check_run_id=34430017406

**Comment by guyharris** [comment]
> Also the commit message has three typos.

Fixed.

**Comment by guyharris** [comment]
> > These changes do not undo the installation and use (TIMEOUT_BIN) of coreutils on macOS.
> 
> That installation didn't appear to prevent a tcpdump build from failing on macOS:
> 
> https://github.com/the-tcpdump-group/tcpdump/pull/1256/checks?check_run_id=34430017406

That installation wasn't being done for tcpdump CI in macOS, which is why it was failing. Any macOS CI that builds and runs `make check` on libpcap needs to install Homebrew coreutils.  Fix incoming in the-tcpdump-group/tcpdump#1257.

That fix still means that any *other* place where "make check" is done on libpcap needs to somehow arrange to install the `timeout` command, unless we provide our own.

**Comment by infrastation** [comment]
Arguably, `TESTRUN` could avoid using `timeout` if it is not available and `TIMEOUT_BIN` is not set (i.e. the user does not mind how long the test takes so long as it passes).

**Comment by infrastation** [comment]
This would mean the test timeout would apply in "other places" by default on most Linuxes, all BSDs, illumos, Solaris CBE and Haiku, and in this development CI setup `timeout` on macOS would be either made available or not used. Would that be better?

**Comment by guyharris** [comment]
> This would mean the test timeout would apply in "other places" by default on most Linuxes, all BSDs, illumos, Solaris CBE and Haiku, and in this development CI setup `timeout` on macOS would be either made available or not used. Would that be better?

That'd work.

**Comment by guyharris** [comment]
Dropped in favor of the-tcpdump-group/tcpdump#1257, which installs GNU coreutils with Homebrew on macOS, so that `gtimeout` is available, and #1421, which avoids using `timeout` if it's not available.

**Pull request closed without merging**
