### PR TITLE
media word type from ifmediareq struct differs on OpenBSD

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by guyharris** [comment]
> media word type from ifmediareq struct differs on OpenBSD

Except on versions where it doesn't differ; older versions of OpenBSD used int.

**Comment by devnexen** [comment]
true. did a small update then.

**Comment by devnexen** [comment]
does it look good ? Just I maintain nmap for OpenBSD which depends on libpcap and would be grateful if this change ended up in the repository. Thanks.

**Comment by guyharris** [comment]
Fixed in f2b77b74364547a5f319bf780f13932e0937f82b.

**Pull request closed without merging**
