### PR TITLE
various improvements and bug fixes for Hurd

### PR DESCRIPTION
**Pull request by infrastation**
This among other things includes a workaround for #1269 and seems to work, but could use more eyeballs, so please proof-read if you can.

### CODE REVIEW

**Comment by infrastation** [comment]
One thing I notice now is that `pcap_setfilter_hurd()` does not need to test if the first argument is `NULL` because the function call happens from a function pointer in the same `pcap_t`, which implies the latter is not `NULL`.

Another thing is that the calls to `pcap_strerror()` should have been `pcapint_fmt_errmsg_for_errno()`.

**Comment by infrastation** [comment]
This is going to be merged in one hour unless anyone sees anything else that requires improvement.

**Comment by fxlb** [comment]
I look at the output of `findalldevstest` on a Hurd system.
It shows no loopback interface. Is it OK?

**Comment by infrastation** [comment]
This is intended, until someone finds a way to add support for loopback packet capture. The existing code cannot do that.

**Comment by infrastation** [comment]
That is, on GNU/Hurd the attempt to capture on loopback fails with an error. On Haiku it "succeeds", but all packet counters are zero, so perhaps meanwhile it would make sense to disable it there as well.

**Comment by fxlb** [comment]
> so perhaps meanwhile it would make sense to disable it there as well.

Perhaps, indeed.

**Comment by fxlb** [comment]
> The existing code cannot do that.

OK.

**Comment by infrastation** [comment]
Loopback capture in Haiku turns out to be a bug, the bug fix is in the development branch, but is not yet in the beta branch. So that particular issue does not require a workaround.

**Comment by guyharris** [comment]
> Loopback capture in Haiku turns out to be a bug, the bug fix is in the development branch, but is not yet in the beta branch. So that particular issue does not require a workaround.

Should it have a note in doc/README.haiku.md?

(Speaking of "you can open the device but you get no packets", I should add a note in doc/README.macos about monitor-mode captures on newer versions of macOS, at least with newer machines, not giving any packets.  There's apparently something that allows packet capturing, given that the "Sniffer" window in Apple's Wireless Diagnostics captures traffic by doing something and then running tcpdump on the Wi-Fi adapter with `-I`; it may be that it just disassociates the adapter from the network it's on.)

**Comment by infrastation** [comment]
After the bug fix makes it into beta4 updates, it should not be difficult to tell the minimal "hrev" that has loopback capture working. I do not know when this will happen.

**Pull request merged**
