### PR TITLE
Linux: no longer report 'without TPACKET'.

### PR DESCRIPTION
**Pull request by Oppen**

### CODE REVIEW

**Comment by guyharris** [comment]
That should be done as part of a change that removes all checks for `HAVE_PACKET_RING` and `PCAP_SUPPORT_PACKET_RING`, as well as the tests in autoconf and CMake that set `PCAP_SUPPORT_PACKET_RING`.

**Comment by Oppen** [comment]
OK, that makes sense. I thought it was the only remaining omission.
I'll rebase on this same PR if that's OK.

**Comment by guyharris** [comment]
> OK, that makes sense. I thought it was the only remaining omission.

No.  We now have no support for `SOCK_PACKET`, and thus require at least 2.2, but we still don't require turbopacket (which I think means requiring at least 2.4).

> I'll rebase on this same PR if that's OK.

OK.

**Comment by guyharris** [comment]
Needs to be rebased against the tip of the master branch, to resolve the conflicts.

**Pull request closed without merging**
