### PR TITLE
Add hurd support, from debian

### PR DESCRIPTION
**Pull request by LocutusOfBorg**
This is the hurd support, from debian patch

### CODE REVIEW

**Comment by mcr** [comment]
Does this patch depend upon a new autoconf?

**Comment by LocutusOfBorg** [comment]
nope, it should work also without the new autoconf

**Comment by guyharris** [comment]
From a quick look at the current Hurd code in Git, the return value of a BPF filter is used only as a pass/fail indication; it doesn't limit the amount of packet data copied.  For now, it's probably best to use `MAXIMUM_SNAPLEN` rather than 1500 in the filter.

**Comment by infrastation** [comment]
@LocutusOfBorg, would you like to rebase these changes on the current master branch?

**Comment by infrastation** [comment]
Thank you. Do not mind FreeBSD and illumos failures, which are caused by recent Valgrind changes. To try the new code, is the simplest way to setup a VM as described [here](https://www.gnu.org/software/hurd/hurd/running/qemu.html)?

**Comment by LocutusOfBorg** [comment]
Hello, it should be, but also going on irc OFTC/#debian-hurd helps :)

**Comment by sthibaul** [comment]
FI, it builds fine on my hurd box, provided the additional change:

[patch.txt](https://github.com/the-tcpdump-group/libpcap/files/9600838/patch.txt)

**Comment by sthibaul** [comment]
(and autoreconf of course)

**Comment by sthibaul** [comment]
otherwise one gets:

```
gcc  -shared libpcap.so.$MAJOR_VER \
   -o libpcap.so.$VER pcap-hurd.o fad-getad.o  pcap-dbus.o  pcap.o gencode.o optimize.o nametoaddr.o etherent.o fmtutils.o savefile.o sf-pcap.o sf-pcapng.o pcap-common.o bpf_image.o bpf_filter.o bpf_dump.o scanner.o grammar.o strlcat.o strlcpy.o  -lrt -ldbus-1
/usr/bin/ld: cannot find libpcap.so.1: No such file or directory
```

because it's missing the `-soname` parameter

**Comment by infrastation** [comment]
It took 8 years to resolve this due to a number of reasons, one of which is that none of the project maintainers have a working GNU Hurd system.  I tried to rig one up today, but without success.  However, @sthibaul has compile-tested the code and confirmed that the current libpcap binary package (`libpcap0.8:hurd-i386 1.10.1-4`) is functional for the current tcpdump binary package, so the original patch (which has been stable since 2014) and the two follow-up improvements are now in the master branch.

**Comment by guyharris** [comment]
This didn't include CMake support  I took the configure.ac changes and tried to translate them to CMake in #1267 - new platform changes should support both configuration mechanisms.  Please test that as well.

**Pull request merged**
