### PR TITLE
CMake: translate the changes for Hurd support from autotools.

### PR DESCRIPTION
**Pull request by guyharris**
Untested, but it should handle Hurd the same way it's handled by the configure script.

### CODE REVIEW

**Comment by fxlb** [comment]
@sthibaul @LocutusOfBorg 
Please, could you test the Hurd support in libpcap with CMake build via:
`MATRIX_CMAKE=yes ./build_matrix.sh`

**Comment by sthibaul** [comment]
There were a couple harmless warnings, fixed by https://github.com/the-tcpdump-group/libpcap/pull/1268

**Comment by fxlb** [comment]
FYI, full test (Autoconf and CMake) can be done with:
`./build_matrix.sh`

**Comment by sthibaul** [comment]
Yes, with #1268 applied, it all builds fine (`Tested setup count: 16`)

**Pull request merged**
