### PR TITLE
CMAKE_C_LIBRARY_ARCHITECTURE

### PR DESCRIPTION
**Pull request by bscottm**
Set CMAKE_C_LIBRARY_ARCHITECTURE for newer versions of CMake. The
CMAKE_LIBRARY_ARCHITECTURE is a meta-variable that is set from the
value of CMAKE_\<LANG\>_LIBRARY_ARCHITECTURE in at least 3.15 onward.

Ref #844 (Committed change to a separate branch to avoid merge commits.)

### CODE REVIEW

**Comment by bscottm** [comment]
`CMAKE_LIBRARY_ARCHITECTURE`'s inheritance from the current language has been part of the CMake documentation since at least 3.10 and onward.

**Comment by fxlb** [comment]
First, a rebase on the-tcpdump-group:master is needed.

**Comment by bscottm** [comment]
Rebased.

**Comment by bscottm** [comment]
Rebased and sync-ed my repo.

**Pull request merged**
