### PR TITLE
fix typo on manpage install

### PR DESCRIPTION
**Pull request by busterb**
This causes errors when doing make install twice because the manpage is not properly removed.

### CODE REVIEW

**Comment by mcr** [comment]
We drifted from the question of the man pages.
I agree that it's annoying, the alternative is that people can not compile because they can not install the "right" autoconf tools.  I am open to a post-commit hook, but given that development is now on github, that won't work.
I am manually pulling this up and closing it.

**Comment by mcr** [comment]
This tree contains some 32/64bit tpacket fixes, which I've omitted.

**Comment by mcr** [comment]
I can not find any unmerged pieces from this pull request.
The 32-bit userland on 64-bit kernel is likely still an issue though.

**Comment by busterb** [comment]
Sorry for the scope leakage - I should have submitted this PR from a feature branch.

**Pull request closed without merging**
