### PR TITLE
Add new DLT_ and LINKTYPE_ for Silabs Debug Channel.

### PR DESCRIPTION
**Pull request by tecimovic**
Add a new LINKTYPE_, DLT_ and a DLT_CHOICE for the Silabs Debug Channel protocol.

See: 
   https://github.com/SiliconLabs/java_packet_trace_library/blob/master/doc/debug-channel.md

### CODE REVIEW

**Comment by tecimovic** [comment]
I see in the pull request log that there is already a PR in the queue that uses up 293.
When that is merged in, let me know, I'll rebase and add a commit to change the number to whatever the actual number will finally be...

**Comment by tecimovic** [comment]
Rebased...

**Comment by tecimovic** [comment]
@infrastation : we have some internal work that might depend on when this is merged. It's not a deal-breaker, because we are meanwhile using one of the USER codes, so we can keep doing that, but question remains:
   is there anything holding this up? Any estimates when this PR might be merged?

**Comment by tecimovic** [comment]
Rebased again.

@infrastation @guyharris: Do you need me to do anything else with this to merge it in?

**Comment by guyharris** [comment]
> Do you need me to do anything else with this to merge it in?

We need you to, at minimum, answer the questions I recently asked in the-tcpdump-group/tcpdump-htdocs/#27 and update your spec to provide those answers.

**Comment by tecimovic** [comment]
@infrastation , @guyharris :

I've updated the docs as requested, I've updated the DLT number again to a later one and rebased both PRs in the two repos. Any chance we can get this merged in now?

Our organization has been using the USERx DLTs for many many months now, and we would really at this point be able to have a fixed DLT for our infrastructure work. The longer we wait, the more things will have to change here and there, so we would really appreciate this being merged, so we can then all standardize on our assigned DLT.

Thank you so much!

**Comment by tecimovic** [comment]
@infrastation , @guyharris : 

Any updates? If you need anything from me to get this merged in, please let me know! 

Cheers,
   TImotej

**Comment by infrastation** [comment]
Done via commit c7cd0a1 earlier, closing.

**Comment by infrastation** [comment]
For posterity, `LINKTYPE_SILABS_DEBUG_CHANNEL` became available in libpcap 1.10.6.

**Pull request closed without merging**
