### PR TITLE
Print MAC addresses in findalldevstest.

### PR DESCRIPTION
**Pull request by infrastation**
Any objections to make this change?

### CODE REVIEW

**Comment by fxlb** [comment]
It's better than printing `Address Family: Unknown (17)`. No objection.

**Comment by guyharris** [comment]
On Windows, if `_WIN32_WINNT` is >= 0x0601:

- `AF_LINK` is defined;
- `struct sockaddr_dl` is defined, and has, as members:
   - `sdl_family` (an `ADDRESS_FAMILY`, which is a 16-bit unsigned integer);
   - `sdl_data` (an 8-byte array);
   - `sdl_zero` (a 4-byte array).

**Comment by infrastation** [comment]
Thank you for the details, this convinced me not to try decoding the Windows version of the structure.

**Comment by guyharris** [comment]
> this convinced me not to try decoding the Windows version of the structure.

Yeah, it has nothing obvious that indicates the type or the length of the link-layer address.

**Comment by infrastation** [comment]
Ironically, `struct sockaddr_dl` is much more comprehensible, but I printed it in a way that works correctly on illumos only. I have a bug fix, going to double-check it and commit tomorrow.

**Pull request merged**
