### PR TITLE
Retire support for HP-UX before 10.20.

### PR DESCRIPTION
**Pull request by infrastation**
The changes look correct to me, but additional proof-reading would be appreciated. I don't have means to test the remaining HP-UX support.

### CODE REVIEW

**Comment by guyharris** [comment]
Looks good to me.

> reject these versions in both Autoconf and CMake.

Given that, should we, when testing in the code whether we're building for HP-UX, just test whether any of `_hpux`, `hpux`, and `__hpux` are defined, as per [the operating systems page](https://sourceforge.net/p/predef/wiki/OperatingSystems/) in [the Pre-defined Compiler Macros Wiki](https://sourceforge.net/p/predef/wiki/Home/)?  (They don't show a way of testing the HP-UX version at compile time, but the configure script and CMakeLists.txt handle that.)

**Comment by infrastation** [comment]
I considered switching to `__hpux`, but eventually left `HAVE_HPUX10_20_OR_LATER` in place to make it easy to add code specific only to a later HP-UX version if necessary. If you see a better way to arrange it, please do. The wiki link reminds me: `git grep MSDOS` still returns some conditional (i.e. dead) code, is there any reason to keep it?

**Comment by guyharris** [comment]
> I considered switching to `__hpux`, but eventually left `HAVE_HPUX10_20_OR_LATER` in place to make it easy to add code specific only to a later HP-UX version if necessary. If you see a better way to arrange it, please do.

We can leave it in for now; I suspect there may not be too much in the way of later HP-UX versions, given that 1) Itanium is dead and 2) HPE appear to have no plan to port HP-UX to x86-64 - as far as I know, their plan is to do binary-to-binary translation of Itanium code to x86-64(!) inside an HP-UX emulator atop Linux, and I suspect that, even if they add some features to the emulated HP-UX, it probably won't be tweaks to DLPI that will affect us.

At that point, most packet capture on HPE servers might be done directly on Linux.

> The wiki link reminds me: `git grep MSDOS` still returns some conditional (i.e. dead) code, is there any reason to keep it?

Only if we plan to support a no-capture libpcap for MS-DOS, for use by programs that read capture files.  I don't think we do.

**Comment by infrastation** [comment]
Done. Various documentation updates will be next, and that should be it.

**Comment by infrastation** [comment]
For posterity, [here](https://github.com/cpredef/predef/blob/master/OperatingSystems.md) is a version of the above document with a few additional operating systems.

**Pull request merged**
