### PR TITLE
cmake: Update the minimum required version to 2.8.12 (except Windows)

### PR DESCRIPTION
**Pull request by fxlb**
This change is used to check the CI with cmake minimal 2.8.12.

### CODE REVIEW

**Comment by guyharris** [comment]
OK, so shall we:

- add a note about fixing #1138 to the commit message;
- remove "TEST ONLY:" from the title;
- mark it as no longer a draft;

and merge this?

**Comment by infrastation** [comment]
Whoever gets to commit this change, add a change log line please.

**Comment by fxlb** [comment]
> OK, so shall we:
>     * add a note about fixing [CMake Deprecation Warning at CMakeLists.txt:7 (cmake_minimum_required) #1138](https://github.com/the-tcpdump-group/libpcap/issues/1138) to the commit message;
>     * remove "TEST ONLY:" from the title;
>     * mark it as no longer a draft;
> and merge this?

Ok, I wil do that.

**Comment by fxlb** [comment]
> Whoever gets to commit this change, add a change log line please.

Yes.

**Pull request merged**
